// Autogenerated from Pigeon (v4.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTVersion;

@interface FLTVersion : NSObject
+ (instancetype)makeWithString:(nullable NSString *)string;
@property(nonatomic, copy, nullable) NSString * string;
@end

/// The codec used by FLTExampleApi.
NSObject<FlutterMessageCodec> *FLTExampleApiGetCodec(void);

@protocol FLTExampleApi
/// @return `nil` only when `error != nil`.
- (nullable FLTVersion *)getPlatformVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTExampleApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTExampleApi> *_Nullable api);

NS_ASSUME_NONNULL_END
